### ISSUE TITLE
Hmatrix - from zeros to hero: variable names mistake

### ISSUE THREAD

**Issue by TravisCardwell** [nicaudinet/nicaudinet.github.io#1]
I enjoyed reading your "Hmatrix - from zeros to hero" blog post!

I noticed a mistake of variable names in the first implementation.  `replicate (n * m)` should be `replicate (n_val * m_val)`.  I suspect that you initially named these variables `n` and `m` but changed the names to distinguish them from the type variables of the same names and missed some.  I count three places that need this fix.

I have added your RSS feed to my reader, and I look forward to reading your future blog posts!

**Comment by nicaudinet** [comment]
Thank you for spotting the mistake! That's exactly what happened 😄  I'll fix it now.
